### ISSUE TITLE
ER_WAL_IO: Failed to write to disk

### ISSUE THREAD

**Issue by SHaaD94** [dreadatour/tarantool-locksmith#1]
Potential way to reproduce:
Connect to tarantool which holds locksmith from another tarantool, accuirelock, drop down connection.

2016-11-25 15:48:05.384 [25904] main/104/locks_watchdog I> <Lock uid='48e72434-f09e-4c7e-bb80-edd5aa339707' name='13371515021507648147'> expired and released by watchdog
2016-11-25 15:48:05.384 [25904] main/104/locks_watchdog txn.cc:224 E> ER_WAL_IO: Failed to write to disk
2016-11-25 15:48:05.384 [25904] main/104/locks_watchdog txn.cc:224 E> ER_WAL_IO: Failed to write to disk
Segmentation fault
Current time: 1480063685
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#0  0x40ecf1 in sig_fatal_cb(int)+129
#1  0x7eff97d4a330 in ?
#2  0x4c8710 in fiber_loop+48
#3  0x5ee83f in coro_init+63
#4  (nil) in ?

**Comment by kostja** [comment]
Hi,

What's your tarantool version?

Do you have  a test case?

**Comment by SHaaD94** [comment]
Hi, 
Tarantool 1.7.2-149-g4e9d751
Target: Linux-x86_64-RelWithDebInfo

Sorry, i don't have exact test case, please try steps, which i described earlier.

**Comment by zilveer** [comment]
Was this solved ?
